from django.urls import path
from . import views

urlpatterns=[
        path('',views.index,name='Index Page'),
        path('Login',views.login,name='Login'),
        path('Logout',views.logout,name='Logout'),
        path('Ex1',views.Ex1,name='Exercise 1'),
        path('Ex1/correct',views.correctEx1,name='Results'),
        path('Ex2',views.Ex2,name='Exercise 2'),
        path('Ex2/correct',views.correctEx2,name='Results2'),
        path('Ex3',views.Ex3,name='Exercise 3'),
        path('Ex3/correct',views.correctEx3,name='Results3'),
        path('Ex4',views.Ex4,name='Exercise 4'),
        path('Ex4/correct',views.correctEx4,name='Results4'),
        path('Ex5',views.Ex5,name='Exercise 5'),
        path('Ex5/correct',views.correctEx5,name='Results5'),
        path('Ex6',views.Ex6,name='Exercise 6'),
        path('Ex6/correct',views.correctEx6,name='Results6'),
        path('Ex7',views.Ex7,name='Exercise 7'),
        path('Ex7/correct',views.correctEx7,name='Results7'),
        path('Ex8',views.Ex8,name='Exercise 8'),
        path('Ex8/correct',views.correctEx8,name='Results8'),
        path('Vocabulary1',views.Voc1,name='Vocabulary 1'),
        path('Vocabulary2',views.Voc2,name='Vocabulary 2'),
        path('Vocabulary3',views.Voc3,name='Vocabulary 3'),
        path('Vocabulary4',views.Voc4,name='Vocabulary 4'),
        path('Vocabulary5',views.Voc5,name='Vocabulary 5'),
        path('Verbs1',views.Verbs1,name='Verbs 1'),
        path('Verbs2',views.Verbs2,name='Verbs 2'),
        path('Verbs3',views.Verbs3,name='Verbs 3'),
        path('Verbs4',views.Verbs4,name='Verbs 4'),
        path('About',views.About,name='About'),
        ]
